# Generated by Django 3.2.13 on 2022-06-14 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(db_index=True, max_length=1500, verbose_name='Задание')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('files', models.FileField(blank=True, upload_to='task_files/', verbose_name='Файл')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app_tasks.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksmodels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'tasks',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_task', models.IntegerField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customertags', to='app_tasks.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customertags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Теги работодателя',
                'verbose_name_plural': 'Теги работодателей',
                'db_table': 'CustomerTag',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ContractorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractortasks', to='app_tasks.taskmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractortasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-close_time'],
            },
        ),
        migrations.CreateModel(
            name='ContractorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_point', models.IntegerField(default=0)),
                ('count_task', models.IntegerField(default=0)),
                ('middle_point', models.FloatField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractortags', to='app_tasks.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractortags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Теги исполнителя',
                'verbose_name_plural': 'Теги исполнителей',
                'db_table': 'ContractorTag',
                'ordering': ['-all_point'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1500, verbose_name='Комментарий')),
                ('file', models.FileField(blank=True, upload_to='comment_files/', verbose_name='Файл')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_tasks.contractortask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
