# Generated by Django 4.0.4 on 2022-05-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='files',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='files',
            field=models.FileField(blank=True, upload_to='task_files/'),
        ),
        migrations.DeleteModel(
            name='TaskFileModel',
        ),
    ]
